# Site settings
title: "Marionette.js по-русски"
email: instanceofpro@gmail.com
username: instanceofpro
description: "Marionette.js по-русски"

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title
