# Site settings
title: "Marionette.js по-русски"
email: instanceofpro@gmail.com
username: instanceofpro
description: "Marionette.js по-русски."
baseurl: /marionettejs.ru
version: 1.8.8

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title
