# Site settings
title: "Marionette.js по-русски"
email: sadcitizen@yandex.ru
username: sadcitizen
description: "Marionette.js по-русски."
baseurl: /marionettejs.ru
version: 2.4.3

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
encoding: utf-8
